### ISSUE TITLE
How to get raw JWT?

### ISSUE THREAD

**Issue by pascalw** [MichelBoucey/google-oauth2-jwt#1]
Hi @MichelBoucey.

I'm just learning Haskell and wanted to use your library. I managed to invoke the`getSignedJWT` function which gives me a `String` (in case of error) or a `SignedJWT` if all was good.

Now what I'm struggling with is how I can actually get to the raw value, the actual JWT as a String like type?

I tried using pattern matching like this:

```hs
let (SignedJWT rawJwt) = jwt
```

But this gives me:

```hs
<interactive>:65:6: error:
    Not in scope: data constructor ‘SignedJWT’
```

Can you maybe point me in the right direction? 🙂

**Comment by MichelBoucey** [comment]
Hi @pascalw

The SignedJWT type has a Show instance, which means there is a provided method in the library to derive the type SignedJWT to String
```hs
let rawjwt = show mySignedJWT
```
or something like
```hs
putStrLn $ "My Signed JWT is " ++ show mySignedJWT
```
But I just fix this instance because of a bad automatic deriving Show instance. Please use `google-oauth2-jwt-0.3.0` for the good behavior.

**Comment by pascalw** [comment]
Thanks, that works! 👍
